
export TAG="$CURRENT_BRANCH-${CIRCLE_BUILD_NUM}"

docker build -t $CONTAINER_REGISTRY/$PROJECT_NAME:$TAG -t $CONTAINER_REGISTRY/$PROJECT_NAME:latest -f .
docker push $CONTAINER_REGISTRY/$PROJECT_NAME